### ISSUE TITLE
error when run train.py

### ISSUE THREAD

**Issue by TTTJJJWWW** [leimao/Voice_Converter_CycleGAN#14]
@leimao Hi, when i run 
$ python train.py --train_A_dir ./data/vcc2016_training/SF1 --train_B_dir ./data/vcc2016_training/TM1 --model_dir ./model/sf1_tm1 --model_name sf1_tm1.ckpt --random_seed 0 --validation_A_dir ./data/evaluation_all/SF1 --validation_B_dir ./data/evaluation_all/TM1 --output_dir ./validation_output --tensorboard_log_dir ./log
The memory(8G) will be full and the train process will be sluggish!
What is the problem? I need add memory or just check the software like tf,cuda...
THANKS!

**Comment by leimao** [comment]
Thank you for raising this problem to me. Since I don't have a 8-GB memory GPU to reproduce your problem and none of the other users have reported similar problems, please upload a detailed error log so that we may confirm it is a GPU memory issue. It should be noted that, especially for new TensorFlow users, TensorFlow use as much GPU memory as possible usually, regardless of the model you are using. So if you see the GPU memory is full during training, don't panic and it is normal as long as the program did not raise error. If your problem is just "program sluggish" without any error, I will just say let it run.

**Comment by TTTJJJWWW** [comment]
@leimao  Hi, thank you for reply!
My problem is the system memory will be full by process, so the program can not work with GPU(will killed by system because of memory issue).
At the same time, my GPU is RTX2070 with 8-GB memory, but I think the GPU maybe not the problem for now.
I'm confused, because increasing the system's memory to 32G still doesn't solve this problem. So far, the program has not really used GPU to process data.

**Comment by leimao** [comment]
This is unusual. Please make sure that TensorFlow-GPU was installed correctly on your system. One way to check is that you run a simple neural networks, such as this [one](https://github.com/leimao/Frozen_Graph_TensorFlow), on your system and monitor the GPU usage using `nvidia-smi`. If you found that the GPU was not fully used during training, you need to configure your system properly before you run any kind of deep learning program.

**Comment by TTTJJJWWW** [comment]
@leimao Thank you, I fixed that problem.
