### ISSUE TITLE
It's not an issue, but if i want to map the accent as well as the voice. so let's say i have a phonetic transcription for the audio data and i want to be able to convert accent from domain A to domain B and vice versa. How to achieve this? I thought of the conditional gan approach where you include the additional data to train the model on it as well as the audio data

### ISSUE THREAD

**Issue by nawawy** [leimao/Voice_Converter_CycleGAN#5]

**Comment by leimao** [comment]
Hi Nawawy,

I am not sure how to distinguish between voice and accent. If the accent features could be represented by Mel Cepstral Coefficients (MCEP), which I do believe so, then accent transformation should be achievable using this method. What you have to prepare is the speech audio of one person speaking accent A and another person speaking accent B. Extract the MCEP features and train Cycle-GAN.

However, if the accent features could not be extracted by MCEP features, you will have to think of a good feature representations for the accents and apply them in the CycleGAN.

**Comment by nawawy** [comment]
Hi Lei,

Well  i trained it on speech data of two different dialects and it did not convert the accents it just focuses on the voice. So i guess MCEP only focuses on the voice, However, i have a phonetic transcriptions for the audio and i was wandering how to use them to convert accent as well.

**Comment by leimao** [comment]
Hi Nawaway,

I think this time you used the right word "dialects" instead of "accents". Basically "accents" is just the voice but "dialects" could be a "different" language.

This might be a new interesting topic. I am sure that simply using the CycleGAN in this particular repo will not work for your problem. You may also think this problem as converting between English speeches and French speeches with training data that has the phonetic transcriptions, which is a very hard problem. I did a quick Google search and found no existing solutions to this. You may really get something new out of this! But this may require new models.

I remember Google, or maybe some other big company, has done unsupervised machine translations. But since yours have labeled transcriptions and it is audio data, the problem is different to theirs.

Intuitively, directly using GAN might not be the best solution to this problem. One of the strategies could be translating dialect A back to its transcription, and generate dialect B from the transcription using the speech features from dialect A. Since there are mature speech caption techniques and text-to-speech generation models, I am sure this strategy will work from an engineering perspective.
